services:
  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=sismos24
    volumes:
      - "/home/cdlzs/seismic24/seismic_act_cdmx/postgres_data:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    volumes:
      - "/home/cdlzs/seismic24/seismic_act_cdmx/pgadmin_data:/var/lib/pgadmin"
    ports:
      - "8080:80"
  python_app:  
  build:
    context: .
    dockerfile: Dockerfile
  depends_on:
    - pgdatabase